### PR TITLE
feat: added timezone support

### PR DESCRIPTION
**Pull request by thetejasmagade**
Solves: #4 
Added support for timezone support in `.cron()` method.

New `timezone: string` optional parameter is added in `cron()` method.

### CODE REVIEW

**Review by rohrig — CHANGES_REQUESTED** [review]
This looks great. Could you add a more specific type check for the time zones? It would be great if we get a type error if the timezone is written incorrectly.

**Comment by thetejasmagade** [comment]
Yeah sure 👍

**Comment by thetejasmagade** [comment]
Hey, @rohrig ! Is it right?
```js
try {
  timezone ? cron.schedule(interval, callback, { scheduled: true, timezone: timezone }) : cron.schedule(interval, callback);
} catch (err) {
  throw new TypeError("Invalid time zone specified: " + timezone);
}
```

**Comment by rohrig** [comment]
I was hoping to get auto-completion for the time zones, but it looks like that would be a huge union type. So we can just remove the try-catch and let the original error bubble up. Thanks

**Comment by kyng-cytro** [comment]
> I was hoping to get auto-completion for the time zones, but it looks like that would be a huge union type. So we can just remove the try-catch and let the original error bubble up. Thanks

The auto-completion might be nice. If you don't mind that line being a bit longer we could have a couple and then default to string. I mean something like this 

```ts
 cron: (interval: string, timezone?: "Europe/London" | "America/New_York" | "Africa/Abidjan" | string) => void;
```

We could do the top 5 that way people know what it should look like. haven't tested but it should trick IntelliSense

**Pull request merged**
